---
 - name: Management System Group
   group:
     name: "{{ item.name }}"
     gid: "{{ item.gid | default(omit) }}"
     state: "{{ item.state | default('present') }}"
     system: "{{ item.system | default('no') }}"
   with_items: "{{  management_groups }}"
   when: management_groups is defined

 - name: Create Normal User
   user:
     name: "{{ item }}"
     uid: "{{ management_active_users[item].uid | default(omit) }}"
     password: "{{ management_active_users[item].password | default('!!') }}"
     comment: "{{ management_active_users[item].full_name | default('') }}"
     createhome: "{{ management_active_users[item].createhome | default('yes') }}"
     group: "{{ management_active_users[item].group | default(omit) }}"
     groups: "{{ management_active_users[item].groups | default('') | join(',') }}"
     shell: "{{ management_active_users[item].shell | default('/bin/bash') }}"
     append: "{{ management_active_users[item].append | default('no') }}"
     state: "{{ management_active_users[item].state | default('present') }}"
   with_items: "{{ management_active_users }}"
   when: management_active_users is defined

 - name: Setup Active User Authorized Key
   authorized_key:
     user: "{{ item }}"
     key: "{{ lookup('file', management_ssh_keys_path  ~ management_active_users[item].public_key ) }}"
   with_items: "{{ management_active_users }}"
   when: management_active_users[item].public_key is defined

 - name: Remove Active User Authorized Key
   authorized_key:
     user: "{{ item }}"
     key: "{{ lookup('file', management_ssh_keys_path  ~ management_active_users[item].remove_public_key ) }}"
     state: absent
   with_items: "{{ management_active_users }}"
   when: management_active_users[item].remove_public_key is defined

 - name: Remove Normal User
   user:
     name: "{{ item }}"
     remove: "{{ item.remove | default('yes') }}"
     state: "{{ item.state | default('absent') }}"
   with_items: "{{ management_remove_users }}"
   when: management_remove_users is defined
